 version: '3.3'
 services:
   postgres:
     container_name: postgres
     image: 'postgres:latest'
     environment:
       POSTGRES_USER: myuser
       POSTGRES_PASSWORD: secret
       POSTGRES_DB: mydatabase
       POSTGRES_HOST_AUTH_METHOD: trust
     ports:
       - 35432:5432