create table users
(
    id       bigint generated by default as identity
        primary key,
    email    varchar(255) NOT NULL,
    name     varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    role     varchar(255) NOT NULL
);

alter table users
    owner to myuser;
