create table users
(
    id       bigint generated by default as identity
        primary key,
    email    varchar(255),
    name     varchar(255),
    password varchar(255),
    role     varchar(255)
);

alter table users
    owner to myuser;
